import { afterAll, beforeEach, describe, expect, test } from "bun:test";
import { createRepo, createSql, migrateSchema, type RodPurchaseSpec } from "./index.ts";

const databaseUrl = process.env.TEST_DATABASE_URL;
if (databaseUrl !== undefined && !new URL(databaseUrl).pathname.endsWith("_test")) {
  throw new Error("TEST_DATABASE_URL must name a disposable database ending in _test");
}

const sql = databaseUrl === undefined ? null : createSql(databaseUrl);
const carbon: RodPurchaseSpec = {
  rodId: "carbon",
  prerequisite: "basic",
  price: 2_500,
  recipe: [
    { point: 1, count: 4 },
    { point: 2, count: 2 },
  ],
};
const titanium: RodPurchaseSpec = {
  rodId: "titanium",
  prerequisite: "carbon",
  price: 12_000,
  recipe: [
    { point: 2, count: 4 },
    { point: 3, count: 2 },
  ],
};

async function resetSchema(): Promise<void> {
  await sql!.unsafe("DROP SCHEMA public CASCADE; CREATE SCHEMA public");
}

async function createAvailableCatch(
  userId: number,
  chatId: number,
  point: number,
  price: number,
  name = `Fish ${point}-${price}`,
): Promise<void> {
  await sql!`INSERT INTO caught_fishes
    (username, user_id, fish_name, fish_weight, fish_size, fish_rarity, fish_rarity_point, fish_price, chat_id, inventory_state)
    VALUES ('Test', ${userId}, ${name}, 1000, 30, 'Test', ${point}, ${price}, ${chatId}, 'available')`;
}

describe.skipIf(databaseUrl === undefined)("Repo inventory economy integration", () => {
  beforeEach(async () => {
    await resetSchema();
  });

  afterAll(async () => {
    await sql!.end();
  });

  test("migrates historical catches to sold without changing balances", async () => {
    await sql!.unsafe(`CREATE TABLE fishers (
      user_id BIGINT NOT NULL, chat_id BIGINT NOT NULL, user_first_name TEXT NOT NULL,
      user_balance DOUBLE PRECISION NOT NULL DEFAULT 0, PRIMARY KEY (user_id, chat_id)
    );
    CREATE TABLE caught_fishes (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, username TEXT NOT NULL, user_id BIGINT NOT NULL,
      fish_name TEXT NOT NULL, fish_weight DOUBLE PRECISION NOT NULL, fish_size DOUBLE PRECISION NOT NULL,
      fish_rarity TEXT NOT NULL, fish_rarity_point INTEGER NOT NULL, fish_price DOUBLE PRECISION NOT NULL, chat_id BIGINT NOT NULL
    );
    INSERT INTO fishers VALUES (1, -100, 'Legacy', 777);
    INSERT INTO caught_fishes (username, user_id, fish_name, fish_weight, fish_size, fish_rarity, fish_rarity_point, fish_price, chat_id)
      VALUES ('Legacy', 1, 'Old fish', 1000, 30, 'Old', 1, 300, -100);`);
    await migrateSchema(sql!);

    const rows = (await sql!`SELECT inventory_state FROM caught_fishes`) as Array<{ inventory_state: string }>;
    const balances = (await sql!`SELECT user_balance FROM fishers`) as Array<{ user_balance: number }>;
    expect(rows).toEqual([{ inventory_state: "sold" }]);
    expect(Number(balances[0]!.user_balance)).toBe(777);
  });

  test("records available catches, sells once, and bounds bulk sale by preview ID", async () => {
    await migrateSchema(sql!);
    const repo = createRepo(sql!);
    await repo.ensureFisher(1, -100, "Player");
    await repo.recordCatch({ username: "Player", userId: 1, chatId: -100, fishName: "One", rarity: "Common", point: 1, sizeCm: 30, weightG: 1000, price: 100 });
    expect((await repo.getFisher(1, -100))!.balance).toBe(0);
    const page = await repo.getInventoryPage(1, -100, 1, 5);
    expect(page.fishes).toHaveLength(1);
    expect(await repo.sellFish(1, -100, page.fishes[0]!.id)).toEqual({ status: "sold", count: 1, total: 100 });
    expect(await repo.sellFish(1, -100, page.fishes[0]!.id)).toEqual({ status: "not_available" });
    expect(await repo.sellFish(1, -101, page.fishes[0]!.id)).toEqual({ status: "not_available" });

    await createAvailableCatch(1, -100, 1, 200, "Old bulk");
    const preview = await repo.getRaritySalePreview(1, -100, 1);
    expect(preview).not.toBeNull();
    await createAvailableCatch(1, -100, 1, 999, "New bulk");
    expect(await repo.sellRarity(1, -100, 1, preview!.maxFishId)).toEqual({ status: "sold", count: 1, total: 200 });
    expect((await repo.getFisher(1, -100))!.balance).toBe(300);
    expect((await repo.getInventoryPage(1, -100, 1, 5)).fishes.map((fish) => fish.price)).toEqual([999]);
  });

  test("reports the exact missing recipe rarity without changing resources", async () => {
    await migrateSchema(sql!);
    const repo = createRepo(sql!);
    await repo.ensureFisher(1, -100, "Player");
    for (const price of [100, 200, 300, 400]) await createAvailableCatch(1, -100, 1, price);
    await sql!`UPDATE fishers SET user_balance = 2500 WHERE user_id = 1 AND chat_id = -100`;

    expect(await repo.purchaseRod(1, -100, carbon)).toEqual({
      status: "insufficient_fish",
      point: 2,
      required: 2,
      available: 0,
    });
    expect((await repo.getFisher(1, -100))!.balance).toBe(2500);
    expect((await repo.getInventoryPage(1, -100, 1, 5)).totalCount).toBe(4);
    expect(await repo.listPurchasedRodIds(1, -100)).toEqual([]);
    expect(await repo.getEquippedRodId(1, -100)).toBe("basic");
  });

  test("purchase failures are atomic and success spends the cheapest exact recipe", async () => {
    await migrateSchema(sql!);
    const repo = createRepo(sql!);
    await repo.ensureFisher(1, -100, "Player");
    await createAvailableCatch(1, -100, 1, 400);
    await createAvailableCatch(1, -100, 1, 100);
    await createAvailableCatch(1, -100, 1, 300);
    await createAvailableCatch(1, -100, 1, 200);
    await createAvailableCatch(1, -100, 2, 600);
    await createAvailableCatch(1, -100, 2, 500);

    expect(await repo.purchaseRod(1, -100, titanium)).toEqual({ status: "missing_prerequisite", rodId: "carbon" });
    expect(await repo.purchaseRod(1, -100, carbon)).toEqual({ status: "insufficient_balance", required: 2500, available: 0 });
    await createAvailableCatch(1, -100, 1, 999);
    await createAvailableCatch(1, -100, 2, 999);
    await sql!`UPDATE fishers SET user_balance = 2500 WHERE user_id = 1 AND chat_id = -100`;
    const purchased = await repo.purchaseRod(1, -100, carbon);
    expect(purchased).toEqual({ status: "purchased", balance: 0 });
    expect(await repo.getEquippedRodId(1, -100)).toBe("carbon");
    expect(await repo.equipRod(1, -100, "basic")).toEqual({ status: "equipped" });
    expect(await repo.equipRod(1, -100, "carbon")).toEqual({ status: "equipped" });
    expect(await repo.listPurchasedRodIds(1, -100)).toEqual(["carbon"]);
    const rows = (await sql!`SELECT fish_price, inventory_state FROM caught_fishes ORDER BY fish_price`) as Array<{
      fish_price: number;
      inventory_state: string;
    }>;
    expect(rows).toEqual([
      { fish_price: 100, inventory_state: "spent" },
      { fish_price: 200, inventory_state: "spent" },
      { fish_price: 300, inventory_state: "spent" },
      { fish_price: 400, inventory_state: "spent" },
      { fish_price: 500, inventory_state: "spent" },
      { fish_price: 600, inventory_state: "spent" },
      { fish_price: 999, inventory_state: "available" },
      { fish_price: 999, inventory_state: "available" },
    ]);
  });

  test("races sale and purchase transitions without duplicate grants", async () => {
    await migrateSchema(sql!);
    const repo = createRepo(sql!);
    await repo.ensureFisher(1, -100, "Player");
    await createAvailableCatch(1, -100, 1, 150);
    const fishId = (await repo.getInventoryPage(1, -100, 1, 5)).fishes[0]!.id;
    const sales = await Promise.all([repo.sellFish(1, -100, fishId), repo.sellFish(1, -100, fishId)]);
    expect(sales.filter((result) => result.status === "sold")).toHaveLength(1);
    expect((await repo.getFisher(1, -100))!.balance).toBe(150);

    for (const price of [100, 200, 300, 400]) await createAvailableCatch(1, -100, 1, price);
    for (const price of [500, 600]) await createAvailableCatch(1, -100, 2, price);
    await sql!`UPDATE fishers SET user_balance = 2500 WHERE user_id = 1 AND chat_id = -100`;
    const purchases = await Promise.all([repo.purchaseRod(1, -100, carbon), repo.purchaseRod(1, -100, carbon)]);
    expect(purchases.filter((result) => result.status === "purchased")).toHaveLength(1);
    expect(purchases.filter((result) => result.status === "already_owned")).toHaveLength(1);
  });
});
