import { SQL } from "bun";

export type FishTemplateRow = { id: number; name: string; rarity: string; point: number };
export type FishTemplateInsert = { name: string; rarity: string; point: number };
export type FisherRow = { userId: number; chatId: number; firstName: string; balance: number };
export type CooldownRow = { userId: number; firstName: string; lastCatchTime: number };
export type TopFisherRow = { firstName: string; total: number };
export type CatchInsert = {
  username: string;
  userId: number;
  chatId: number;
  fishName: string;
  rarity: string;
  point: number;
  sizeCm: number;
  weightG: number;
  price: number;
};
/** The most recent available catch spent by /cr. */
export type DeletedCatch = { fishName: string; rarity: string; point: number; price: number };
export type InventoryFishRow = {
  id: number;
  name: string;
  rarity: string;
  point: number;
  sizeCm: number;
  weightG: number;
  price: number;
};
export type InventoryPage = {
  fishes: InventoryFishRow[];
  page: number;
  totalCount: number;
  totalValue: number;
};
export type RarityInventorySummary = { point: number; count: number; total: number };
export type RaritySalePreview = { count: number; total: number; maxFishId: number };
export type RodPurchaseSpec = {
  rodId: string;
  prerequisite: string | null;
  price: number;
  recipe: readonly { point: number; count: number }[];
};
export type SaleResult = { status: "sold"; count: number; total: number } | { status: "not_available" };
export type PurchaseResult =
  | { status: "purchased"; balance: number }
  | { status: "already_owned" }
  | { status: "missing_prerequisite"; rodId: string }
  | { status: "insufficient_balance"; required: number; available: number }
  | { status: "insufficient_fish"; point: number; required: number; available: number };
export type EquipResult = { status: "equipped" } | { status: "not_owned" };

const SCHEMA_STATEMENTS = [
  `CREATE TABLE IF NOT EXISTS fishes (
  fish_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  fish_name TEXT NOT NULL,
  fish_rarity TEXT NOT NULL,
  fish_rarity_point INTEGER NOT NULL
)`,
  `CREATE TABLE IF NOT EXISTS fishers (
  user_id BIGINT NOT NULL,
  chat_id BIGINT NOT NULL,
  user_first_name TEXT NOT NULL,
  user_balance DOUBLE PRECISION NOT NULL DEFAULT 0,
  equipped_rod_id TEXT NOT NULL DEFAULT 'basic',
  PRIMARY KEY (user_id, chat_id)
)`,
  `ALTER TABLE fishers ADD COLUMN IF NOT EXISTS equipped_rod_id TEXT NOT NULL DEFAULT 'basic'`,
  `CREATE TABLE IF NOT EXISTS caught_fishes (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username TEXT NOT NULL,
  user_id BIGINT NOT NULL,
  fish_name TEXT NOT NULL,
  fish_weight DOUBLE PRECISION NOT NULL,
  fish_size DOUBLE PRECISION NOT NULL,
  fish_rarity TEXT NOT NULL,
  fish_rarity_point INTEGER NOT NULL,
  fish_price DOUBLE PRECISION NOT NULL,
  chat_id BIGINT NOT NULL,
  inventory_state TEXT NOT NULL DEFAULT 'available',
  CONSTRAINT caught_fishes_inventory_state_check CHECK (inventory_state IN ('available', 'sold', 'spent'))
)`,
  `ALTER TABLE caught_fishes ADD COLUMN IF NOT EXISTS inventory_state TEXT NOT NULL DEFAULT 'sold'`,
  `ALTER TABLE caught_fishes ALTER COLUMN inventory_state SET DEFAULT 'available'`,
  `DO $$ BEGIN
    IF NOT EXISTS (
      SELECT 1 FROM pg_constraint WHERE conname = 'caught_fishes_inventory_state_check'
    ) THEN
      ALTER TABLE caught_fishes ADD CONSTRAINT caught_fishes_inventory_state_check
        CHECK (inventory_state IN ('available', 'sold', 'spent'));
    END IF;
  END $$`,
  `CREATE INDEX IF NOT EXISTS caught_fishes_inventory_lookup_idx
    ON caught_fishes (user_id, chat_id, inventory_state, fish_rarity_point, id)`,
  `CREATE TABLE IF NOT EXISTS fisher_rods (
  user_id BIGINT NOT NULL,
  chat_id BIGINT NOT NULL,
  rod_id TEXT NOT NULL,
  PRIMARY KEY (user_id, chat_id, rod_id),
  FOREIGN KEY (user_id, chat_id) REFERENCES fishers(user_id, chat_id) ON DELETE CASCADE
)`,
  `CREATE TABLE IF NOT EXISTS catch_time (
  user_id BIGINT NOT NULL,
  chat_id BIGINT NOT NULL,
  last_catch_time DOUBLE PRECISION NOT NULL,
  PRIMARY KEY (user_id, chat_id)
)`,
  `CREATE TABLE IF NOT EXISTS chance_up (
  user_id BIGINT NOT NULL,
  chat_id BIGINT NOT NULL,
  PRIMARY KEY (user_id, chat_id)
)`,
];

export function createSql(databaseUrl: string): SQL {
  return new SQL(databaseUrl);
}

export async function migrateSchema(sql: SQL): Promise<void> {
  for (const statement of SCHEMA_STATEMENTS) {
    await sql.unsafe(statement);
  }
}

/**
 * Postgres BIGINT surfaces as number, string, or BigInt depending on the
 * driver; coerce every integer column through this so the repo API is stable.
 */
function asNumber(value: unknown): number {
  return typeof value === "number" ? value : Number(value);
}

function firstNumber(rows: Array<Record<string, unknown>>, column: string): number {
  const row = rows[0];
  return row === undefined ? 0 : asNumber(row[column]);
}

export type Repo = {
  ensureFisher(userId: number, chatId: number, firstName: string): Promise<void>;
  recordCatch(catch_: CatchInsert): Promise<void>;
  deleteLastCatch(userId: number, chatId: number): Promise<DeletedCatch | null>;
  getCatchTime(userId: number, chatId: number): Promise<number | null>;
  upsertCatchTime(userId: number, chatId: number, unixSeconds: number): Promise<void>;
  deleteCatchTime(userId: number, chatId: number): Promise<void>;
  deleteCatchTimes(chatId: number): Promise<number>;
  listCatchTimes(chatId: number): Promise<CooldownRow[]>;
  grantChanceUp(userId: number, chatId: number): Promise<void>;
  hasChanceUp(userId: number, chatId: number): Promise<boolean>;
  consumeChanceUp(userId: number, chatId: number): Promise<boolean>;
  getFisher(userId: number, chatId: number): Promise<FisherRow | null>;
  getInventoryPage(userId: number, chatId: number, page: number, pageSize: number): Promise<InventoryPage>;
  getRarityInventory(userId: number, chatId: number): Promise<RarityInventorySummary[]>;
  getRaritySalePreview(userId: number, chatId: number, point: number): Promise<RaritySalePreview | null>;
  sellFish(userId: number, chatId: number, fishId: number): Promise<SaleResult>;
  sellRarity(userId: number, chatId: number, point: number, maxFishId: number): Promise<SaleResult>;
  purchaseRod(userId: number, chatId: number, spec: RodPurchaseSpec): Promise<PurchaseResult>;
  listPurchasedRodIds(userId: number, chatId: number): Promise<string[]>;
  getEquippedRodId(userId: number, chatId: number): Promise<string | null>;
  equipRod(userId: number, chatId: number, rodId: string): Promise<EquipResult>;
  listTemplates(): Promise<FishTemplateRow[]>;
  replaceAllTemplates(templates: FishTemplateInsert[]): Promise<number>;
  getTopFishers(chatId: number, limit?: number): Promise<TopFisherRow[]>;
  sumUserFishPrice(userId: number, chatId: number): Promise<number>;
  countUserFishes(userId: number, chatId: number): Promise<number>;
  countUserFishesByRarity(userId: number, chatId: number, point: number): Promise<number>;
  insertTemplate(name: string, rarity: string, point: number): Promise<number>;
  deleteTemplate(id: number): Promise<void>;
  loadAllTemplates(): Promise<FishTemplateInsert[]>;
};

export function createRepo(sql: SQL): Repo {
  return {
    async ensureFisher(userId, chatId, firstName): Promise<void> {
      await sql`INSERT INTO fishers (user_id, chat_id, user_first_name, user_balance)
        VALUES (${userId}, ${chatId}, ${firstName}, 0)
        ON CONFLICT DO NOTHING`;
    },
    async recordCatch(catch_): Promise<void> {
      await sql`INSERT INTO caught_fishes
        (username, user_id, fish_name, fish_weight, fish_size, fish_rarity, fish_rarity_point, fish_price, chat_id, inventory_state)
        VALUES (${catch_.username}, ${catch_.userId}, ${catch_.fishName}, ${catch_.weightG}, ${catch_.sizeCm},
        ${catch_.rarity}, ${catch_.point}, ${catch_.price}, ${catch_.chatId}, 'available')`;
    },
    async deleteLastCatch(userId, chatId): Promise<DeletedCatch | null> {
      return sql.begin(async (tx) => {
        const rows = (await tx`UPDATE caught_fishes SET inventory_state = 'spent'
          WHERE id = (SELECT id FROM caught_fishes
            WHERE user_id = ${userId} AND chat_id = ${chatId} AND inventory_state = 'available'
            ORDER BY id DESC LIMIT 1 FOR UPDATE)
          RETURNING fish_name, fish_rarity, fish_rarity_point, fish_price`) as Array<Record<string, unknown>>;
        const row = rows[0];
        if (row === undefined) return null;
        return {
          fishName: String(row.fish_name),
          rarity: String(row.fish_rarity),
          point: asNumber(row.fish_rarity_point),
          price: asNumber(row.fish_price),
        };
      });
    },
    async getCatchTime(userId, chatId): Promise<number | null> {
      const rows = (await sql`SELECT last_catch_time FROM catch_time
        WHERE user_id = ${userId} AND chat_id = ${chatId}`) as Array<{ last_catch_time: unknown }>;
      const row = rows[0];
      return row === undefined ? null : asNumber(row.last_catch_time);
    },
    async upsertCatchTime(userId, chatId, unixSeconds): Promise<void> {
      await sql`INSERT INTO catch_time (user_id, chat_id, last_catch_time)
        VALUES (${userId}, ${chatId}, ${unixSeconds})
        ON CONFLICT (user_id, chat_id) DO UPDATE SET last_catch_time = EXCLUDED.last_catch_time`;
    },
    async deleteCatchTime(userId: number, chatId: number): Promise<void> {
      await sql`DELETE FROM catch_time WHERE user_id = ${userId} AND chat_id = ${chatId}`;
    },
    async deleteCatchTimes(chatId: number): Promise<number> {
      const rows = (await sql`DELETE FROM catch_time WHERE chat_id = ${chatId} RETURNING user_id`) as unknown[];
      return rows.length;
    },
    async listCatchTimes(chatId: number): Promise<CooldownRow[]> {
      const rows = (await sql`SELECT c.user_id, c.last_catch_time, f.user_first_name
        FROM catch_time c
        JOIN fishers f ON f.user_id = c.user_id AND f.chat_id = c.chat_id
        WHERE c.chat_id = ${chatId}
        ORDER BY f.user_first_name, c.user_id`) as Array<Record<string, unknown>>;
      return rows.map((row) => ({
        userId: asNumber(row.user_id),
        firstName: String(row.user_first_name),
        lastCatchTime: asNumber(row.last_catch_time),
      }));
    },
    async grantChanceUp(userId: number, chatId: number): Promise<void> {
      await sql`INSERT INTO chance_up (user_id, chat_id)
        VALUES (${userId}, ${chatId})
        ON CONFLICT (user_id, chat_id) DO NOTHING`;
    },
    async hasChanceUp(userId: number, chatId: number): Promise<boolean> {
      const rows = (await sql`SELECT user_id FROM chance_up
        WHERE user_id = ${userId} AND chat_id = ${chatId}`) as unknown[];
      return rows.length > 0;
    },
    async consumeChanceUp(userId: number, chatId: number): Promise<boolean> {
      const rows = (await sql`DELETE FROM chance_up
        WHERE user_id = ${userId} AND chat_id = ${chatId}
        RETURNING user_id`) as unknown[];
      return rows.length > 0;
    },
    async getFisher(userId: number, chatId: number): Promise<FisherRow | null> {
      const rows = (await sql`SELECT user_id, chat_id, user_first_name, user_balance FROM fishers
        WHERE user_id = ${userId} AND chat_id = ${chatId}`) as Array<Record<string, unknown>>;
      const row = rows[0];
      if (row === undefined) return null;
      return {
        userId: asNumber(row.user_id),
        chatId: asNumber(row.chat_id),
        firstName: String(row.user_first_name),
        balance: asNumber(row.user_balance),
      };
    },
    async getInventoryPage(userId, chatId, page, pageSize): Promise<InventoryPage> {
      const totals = (await sql`SELECT COUNT(*)::int AS count, COALESCE(SUM(fish_price), 0) AS total
        FROM caught_fishes WHERE user_id = ${userId} AND chat_id = ${chatId} AND inventory_state = 'available'`) as Array<
        Record<string, unknown>
      >;
      const totalCount = firstNumber(totals, "count");
      const totalValue = firstNumber(totals, "total");
      const lastPage = Math.max(1, Math.ceil(totalCount / pageSize));
      const currentPage = Math.min(Math.max(1, page), lastPage);
      const rows = (await sql`SELECT id, fish_name, fish_rarity, fish_rarity_point, fish_size, fish_weight, fish_price
        FROM caught_fishes
        WHERE user_id = ${userId} AND chat_id = ${chatId} AND inventory_state = 'available'
        ORDER BY id DESC LIMIT ${pageSize} OFFSET ${(currentPage - 1) * pageSize}`) as Array<Record<string, unknown>>;
      return {
        fishes: rows.map((row) => ({
          id: asNumber(row.id),
          name: String(row.fish_name),
          rarity: String(row.fish_rarity),
          point: asNumber(row.fish_rarity_point),
          sizeCm: asNumber(row.fish_size),
          weightG: asNumber(row.fish_weight),
          price: asNumber(row.fish_price),
        })),
        page: currentPage,
        totalCount,
        totalValue,
      };
    },
    async getRarityInventory(userId, chatId): Promise<RarityInventorySummary[]> {
      const rows = (await sql`SELECT fish_rarity_point, COUNT(*)::int AS count, COALESCE(SUM(fish_price), 0) AS total
        FROM caught_fishes
        WHERE user_id = ${userId} AND chat_id = ${chatId} AND inventory_state = 'available'
        GROUP BY fish_rarity_point ORDER BY fish_rarity_point`) as Array<Record<string, unknown>>;
      return rows.map((row) => ({
        point: asNumber(row.fish_rarity_point),
        count: asNumber(row.count),
        total: asNumber(row.total),
      }));
    },
    async getRaritySalePreview(userId, chatId, point): Promise<RaritySalePreview | null> {
      const rows = (await sql`SELECT COUNT(*)::int AS count, COALESCE(SUM(fish_price), 0) AS total, MAX(id) AS max_fish_id
        FROM caught_fishes
        WHERE user_id = ${userId} AND chat_id = ${chatId} AND fish_rarity_point = ${point}
          AND inventory_state = 'available'`) as Array<Record<string, unknown>>;
      const row = rows[0];
      if (row === undefined || asNumber(row.count) === 0) return null;
      return { count: asNumber(row.count), total: asNumber(row.total), maxFishId: asNumber(row.max_fish_id) };
    },
    async sellFish(userId, chatId, fishId): Promise<SaleResult> {
      return sql.begin(async (tx) => {
        const rows = (await tx`UPDATE caught_fishes SET inventory_state = 'sold'
          WHERE id = ${fishId} AND user_id = ${userId} AND chat_id = ${chatId} AND inventory_state = 'available'
          RETURNING fish_price`) as Array<Record<string, unknown>>;
        const row = rows[0];
        if (row === undefined) return { status: "not_available" };
        const total = asNumber(row.fish_price);
        await tx`UPDATE fishers SET user_balance = user_balance + ${total}
          WHERE user_id = ${userId} AND chat_id = ${chatId}`;
        return { status: "sold", count: 1, total };
      });
    },
    async sellRarity(userId, chatId, point, maxFishId): Promise<SaleResult> {
      return sql.begin(async (tx) => {
        const rows = (await tx`WITH selected AS (
            SELECT id, fish_price FROM caught_fishes
            WHERE user_id = ${userId} AND chat_id = ${chatId} AND fish_rarity_point = ${point}
              AND id <= ${maxFishId} AND inventory_state = 'available'
            FOR UPDATE
          ), sold AS (
            UPDATE caught_fishes AS fish SET inventory_state = 'sold'
            FROM selected WHERE fish.id = selected.id
            RETURNING selected.fish_price
          )
          SELECT COUNT(*)::int AS count, COALESCE(SUM(fish_price), 0) AS total FROM sold`) as Array<Record<string, unknown>>;
        const count = firstNumber(rows, "count");
        if (count === 0) return { status: "not_available" };
        const total = firstNumber(rows, "total");
        await tx`UPDATE fishers SET user_balance = user_balance + ${total}
          WHERE user_id = ${userId} AND chat_id = ${chatId}`;
        return { status: "sold", count, total };
      });
    },
    async purchaseRod(userId, chatId, spec): Promise<PurchaseResult> {
      return sql.begin(async (tx) => {
        const fisherRows = (await tx`SELECT user_balance FROM fishers
          WHERE user_id = ${userId} AND chat_id = ${chatId} FOR UPDATE`) as Array<Record<string, unknown>>;
        const fisher = fisherRows[0];
        if (fisher === undefined) throw new Error("purchaseRod requires an existing fisher");
        if (spec.rodId === "basic") return { status: "already_owned" };
        const owned = (await tx`SELECT 1 FROM fisher_rods
          WHERE user_id = ${userId} AND chat_id = ${chatId} AND rod_id = ${spec.rodId}`) as Array<Record<string, unknown>>;
        if (owned.length > 0) return { status: "already_owned" };
        if (spec.prerequisite !== null && spec.prerequisite !== "basic") {
          const prerequisite = (await tx`SELECT 1 FROM fisher_rods
            WHERE user_id = ${userId} AND chat_id = ${chatId} AND rod_id = ${spec.prerequisite}`) as Array<
            Record<string, unknown>
          >;
          if (prerequisite.length === 0) return { status: "missing_prerequisite", rodId: spec.prerequisite };
        }
        const balance = asNumber(fisher.user_balance);
        if (balance < spec.price) return { status: "insufficient_balance", required: spec.price, available: balance };
        const selectedIds: number[] = [];
        for (const requirement of spec.recipe) {
          const catches = (await tx`SELECT id FROM caught_fishes
            WHERE user_id = ${userId} AND chat_id = ${chatId} AND fish_rarity_point = ${requirement.point}
              AND inventory_state = 'available'
            ORDER BY fish_price, id LIMIT ${requirement.count} FOR UPDATE`) as Array<Record<string, unknown>>;
          if (catches.length < requirement.count) {
            return {
              status: "insufficient_fish",
              point: requirement.point,
              required: requirement.count,
              available: catches.length,
            };
          }
          selectedIds.push(...catches.map((catch_) => asNumber(catch_.id)));
        }
        for (const fishId of selectedIds) {
          await tx`UPDATE caught_fishes SET inventory_state = 'spent'
            WHERE id = ${fishId} AND user_id = ${userId} AND chat_id = ${chatId} AND inventory_state = 'available'`;
        }
        await tx`UPDATE fishers SET user_balance = user_balance - ${spec.price}, equipped_rod_id = ${spec.rodId}
          WHERE user_id = ${userId} AND chat_id = ${chatId}`;
        await tx`INSERT INTO fisher_rods (user_id, chat_id, rod_id) VALUES (${userId}, ${chatId}, ${spec.rodId})`;
        return { status: "purchased", balance: balance - spec.price };
      });
    },
    async listPurchasedRodIds(userId, chatId): Promise<string[]> {
      const rows = (await sql`SELECT rod_id FROM fisher_rods
        WHERE user_id = ${userId} AND chat_id = ${chatId} AND rod_id <> 'basic' ORDER BY rod_id`) as Array<Record<string, unknown>>;
      return rows.map((row) => String(row.rod_id));
    },
    async getEquippedRodId(userId, chatId): Promise<string | null> {
      const rows = (await sql`SELECT equipped_rod_id FROM fishers
        WHERE user_id = ${userId} AND chat_id = ${chatId}`) as Array<Record<string, unknown>>;
      const row = rows[0];
      return row === undefined ? null : String(row.equipped_rod_id);
    },
    async equipRod(userId, chatId, rodId): Promise<EquipResult> {
      if (rodId === "basic") {
        const result = await sql`UPDATE fishers SET equipped_rod_id = ${rodId}
          WHERE user_id = ${userId} AND chat_id = ${chatId}`;
        return result.count === 1 ? { status: "equipped" } : { status: "not_owned" };
      }
      const result = await sql`UPDATE fishers SET equipped_rod_id = ${rodId}
        WHERE user_id = ${userId} AND chat_id = ${chatId}
          AND EXISTS (SELECT 1 FROM fisher_rods r WHERE r.user_id = fishers.user_id
            AND r.chat_id = fishers.chat_id AND r.rod_id = ${rodId})`;
      return result.count === 1 ? { status: "equipped" } : { status: "not_owned" };
    },
    async getTopFishers(chatId, limit = 10): Promise<TopFisherRow[]> {
      const rows = (await sql`SELECT f.user_first_name, COALESCE(SUM(c.fish_price), 0) AS total
        FROM fishers f
        LEFT JOIN caught_fishes c ON c.user_id = f.user_id AND c.chat_id = f.chat_id
        WHERE f.chat_id = ${chatId}
        GROUP BY f.user_id, f.user_first_name
        ORDER BY total DESC
        LIMIT ${limit}`) as Array<Record<string, unknown>>;
      return rows.map((row) => ({ firstName: String(row.user_first_name), total: asNumber(row.total) }));
    },
    async sumUserFishPrice(userId, chatId): Promise<number> {
      const rows = (await sql`SELECT COALESCE(SUM(fish_price), 0) AS total FROM caught_fishes
        WHERE user_id = ${userId} AND chat_id = ${chatId}`) as Array<Record<string, unknown>>;
      return firstNumber(rows, "total");
    },
    async countUserFishes(userId, chatId): Promise<number> {
      const rows = (await sql`SELECT COUNT(*)::int AS n FROM caught_fishes
        WHERE user_id = ${userId} AND chat_id = ${chatId}`) as Array<Record<string, unknown>>;
      return firstNumber(rows, "n");
    },
    async countUserFishesByRarity(userId, chatId, point): Promise<number> {
      const rows = (await sql`SELECT COUNT(*)::int AS n FROM caught_fishes
        WHERE user_id = ${userId} AND chat_id = ${chatId} AND fish_rarity_point = ${point}`) as Array<
        Record<string, unknown>
      >;
      return firstNumber(rows, "n");
    },
    async listTemplates(): Promise<FishTemplateRow[]> {
      const rows = (await sql`SELECT fish_id, fish_name, fish_rarity, fish_rarity_point FROM fishes ORDER BY fish_id`) as Array<
        Record<string, unknown>
      >;
      return rows.map((row) => ({
        id: asNumber(row.fish_id),
        name: String(row.fish_name),
        rarity: String(row.fish_rarity),
        point: asNumber(row.fish_rarity_point),
      }));
    },
    async replaceAllTemplates(templates): Promise<number> {
      return sql.begin(async (tx) => {
        await tx`DELETE FROM fishes`;
        for (const template of templates) {
          await tx`INSERT INTO fishes (fish_name, fish_rarity, fish_rarity_point)
            VALUES (${template.name}, ${template.rarity}, ${template.point})`;
        }
        return templates.length;
      });
    },
    async insertTemplate(name, rarity, point): Promise<number> {
      const rows = (await sql`INSERT INTO fishes (fish_name, fish_rarity, fish_rarity_point)
        VALUES (${name}, ${rarity}, ${point}) RETURNING fish_id`) as Array<Record<string, unknown>>;
      const row = rows[0];
      if (row === undefined) throw new Error("INSERT INTO fishes returned no fish_id");
      return asNumber(row.fish_id);
    },
    async deleteTemplate(id): Promise<void> {
      await sql`DELETE FROM fishes WHERE fish_id = ${id}`;
    },
    async loadAllTemplates(): Promise<FishTemplateInsert[]> {
      const rows = (await sql`SELECT fish_name, fish_rarity, fish_rarity_point FROM fishes ORDER BY fish_id`) as Array<
        Record<string, unknown>
      >;
      return rows.map((row) => ({ name: String(row.fish_name), rarity: String(row.fish_rarity), point: asNumber(row.fish_rarity_point) }));
    },
  };
}
