import { afterAll, beforeEach, describe, expect, test } from "bun:test";
import { createRepo, createSql, migrateSchema, type CatchInsert, type CreateTradeResult, type RodPurchaseSpec, type TradeRow } from "./index.ts";
import { NET_DURATION_SECONDS } from "../features/nets/net.ts";

const databaseUrl = process.env.TEST_DATABASE_URL;
if (databaseUrl !== undefined && !new URL(databaseUrl).pathname.endsWith("_test")) {
  throw new Error("TEST_DATABASE_URL must name a disposable database ending in _test");
}

const sql = databaseUrl === undefined ? null : createSql(databaseUrl);
const carbon: RodPurchaseSpec = {
  rodId: "carbon",
  prerequisite: "basic",
  price: 2_500,
  recipe: [
    { point: 1, count: 4 },
    { point: 2, count: 2 },
  ],
};
const titanium: RodPurchaseSpec = {
  rodId: "titanium",
  prerequisite: "carbon",
  price: 12_000,
  recipe: [
    { point: 2, count: 4 },
    { point: 3, count: 2 },
  ],
};

async function resetSchema(): Promise<void> {
  await sql!.unsafe("DROP SCHEMA public CASCADE; CREATE SCHEMA public");
}

async function createAvailableCatch(
  userId: number,
  chatId: number,
  point: number,
  price: number,
  name = `Fish ${point}-${price}`,
): Promise<void> {
  await sql!`INSERT INTO caught_fishes
    (username, user_id, fish_name, fish_weight, fish_size, fish_rarity, fish_rarity_point, fish_price, chat_id, inventory_state)
    VALUES ('Test', ${userId}, ${name}, 1000, 30, 'Test', ${point}, ${price}, ${chatId}, 'available')`;
}

afterAll(async () => {
  if (sql !== null) await sql.end();
});

describe.skipIf(databaseUrl === undefined)("Repo inventory economy integration", () => {
  beforeEach(async () => {
    await resetSchema();
  });

  test("migrates historical catches to sold without changing balances", async () => {
    await sql!.unsafe(`CREATE TABLE fishers (
      user_id BIGINT NOT NULL, chat_id BIGINT NOT NULL, user_first_name TEXT NOT NULL,
      user_balance DOUBLE PRECISION NOT NULL DEFAULT 0, PRIMARY KEY (user_id, chat_id)
    );
    CREATE TABLE caught_fishes (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, username TEXT NOT NULL, user_id BIGINT NOT NULL,
      fish_name TEXT NOT NULL, fish_weight DOUBLE PRECISION NOT NULL, fish_size DOUBLE PRECISION NOT NULL,
      fish_rarity TEXT NOT NULL, fish_rarity_point INTEGER NOT NULL, fish_price DOUBLE PRECISION NOT NULL, chat_id BIGINT NOT NULL
    );
    INSERT INTO fishers VALUES (1, -100, 'Legacy', 777);
    INSERT INTO caught_fishes (username, user_id, fish_name, fish_weight, fish_size, fish_rarity, fish_rarity_point, fish_price, chat_id)
      VALUES ('Legacy', 1, 'Old fish', 1000, 30, 'Old', 1, 300, -100);`);
    await migrateSchema(sql!);

    const rows = (await sql!`SELECT inventory_state FROM caught_fishes`) as Array<{ inventory_state: string }>;
    const balances = (await sql!`SELECT user_balance FROM fishers`) as Array<{ user_balance: number }>;
    expect(rows).toEqual([{ inventory_state: "sold" }]);
    expect(Number(balances[0]!.user_balance)).toBe(777);
  });

  test("records available catches, sells once, and bounds bulk sale by preview ID", async () => {
    await migrateSchema(sql!);
    const repo = createRepo(sql!);
    await repo.ensureFisher(1, -100, "Player");
    await repo.recordCatch({ username: "Player", userId: 1, chatId: -100, fishName: "One", rarity: "Common", point: 1, sizeCm: 30, weightG: 1000, price: 100, fishModifierId: null, fishModifierName: null, fishModifierRarity: null });
    expect((await repo.getFisher(1, -100))!.balance).toBe(0);
    const page = await repo.getInventoryPage(1, -100, 1, 5);
    expect(page.fishes).toHaveLength(1);
    expect(await repo.sellFish(1, -100, page.fishes[0]!.id)).toEqual({ status: "sold", count: 1, total: 100 });
    expect(await repo.sellFish(1, -100, page.fishes[0]!.id)).toEqual({ status: "not_available" });
    expect(await repo.sellFish(1, -101, page.fishes[0]!.id)).toEqual({ status: "not_available" });

    await createAvailableCatch(1, -100, 1, 200, "Old bulk");
    const preview = await repo.getRaritySalePreview(1, -100, 1);
    expect(preview).not.toBeNull();
    await createAvailableCatch(1, -100, 1, 999, "New bulk");
    expect(await repo.sellRarity(1, -100, 1, preview!.maxFishId)).toEqual({ status: "sold", count: 1, total: 200 });
    expect((await repo.getFisher(1, -100))!.balance).toBe(300);
    expect((await repo.getInventoryPage(1, -100, 1, 5)).fishes.map((fish) => fish.price)).toEqual([999]);
  });

  test("marks an admin-removed catch as removed without changing balance", async () => {
    await migrateSchema(sql!);
    const repo = createRepo(sql!);
    await repo.ensureFisher(1, -100, "Player");
    await repo.recordCatch({
      username: "Player",
      userId: 1,
      chatId: -100,
      fishName: "Removed",
      rarity: "Common",
      point: 1,
      sizeCm: 30,
      weightG: 1000,
      price: 100,
      fishModifierId: null,
      fishModifierName: null,
      fishModifierRarity: null,
    });

    expect(await repo.deleteLastCatch(1, -100)).toMatchObject({ fishName: "Removed", price: 100 });
    expect((await repo.getFisher(1, -100))!.balance).toBe(0);
    expect((await repo.getInventoryPage(1, -100, 1, 5)).totalCount).toBe(0);
    const rows = (await sql!`SELECT inventory_state FROM caught_fishes`) as Array<{ inventory_state: string }>;
    expect(rows).toEqual([{ inventory_state: "removed" }]);
  });

  test("removes a selected inventory fish and resets a removed equipped rod", async () => {
    await migrateSchema(sql!);
    const repo = createRepo(sql!);
    await repo.ensureFisher(1, -100, "Player");
    await createAvailableCatch(1, -100, 1, 100, "Selected");
    const fishId = (await repo.getInventoryPage(1, -100, 1, 5)).fishes[0]!.id;

    expect(await repo.removeInventoryFish(1, -100, fishId)).toBe(true);
    expect(await repo.removeInventoryFish(1, -100, fishId)).toBe(false);
    expect((await repo.getInventoryPage(1, -100, 1, 5)).totalCount).toBe(0);

    await sql!`INSERT INTO fisher_rods (user_id, chat_id, rod_id) VALUES (1, -100, 'carbon')`;
    await sql!`UPDATE fishers SET equipped_rod_id = 'carbon' WHERE user_id = 1 AND chat_id = -100`;
    expect(await repo.removePurchasedRod(1, -100, "carbon")).toBe(true);
    expect(await repo.removePurchasedRod(1, -100, "carbon")).toBe(false);
    expect(await repo.getEquippedRodId(1, -100)).toBe("basic");

    expect(await repo.grantPurchasedRod(1, -100, "carbon")).toBe(true);
    expect(await repo.grantPurchasedRod(1, -100, "carbon")).toBe(false);
    expect(await repo.listPurchasedRodIds(1, -100)).toEqual(["carbon"]);
  });

  test("stores modifier fields on new catches and reads legacy rows as null", async () => {
    await migrateSchema(sql!);
    const repo = createRepo(sql!);
    await repo.ensureFisher(1, -100, "Player");
    await repo.ensureFisher(2, -100, "Other");
    // A row written before the modifier columns existed reads back without error.
    await createAvailableCatch(1, -100, 1, 100, "Legacy");
    await createAvailableCatch(2, -100, 2, 200, "Щука");
    await repo.recordCatch({
      username: "Player",
      userId: 1,
      chatId: -100,
      fishName: "Окунь",
      rarity: "Обычный",
      point: 1,
      sizeCm: 17.66,
      weightG: 440.62,
      price: 355.25,
      fishModifierId: "golden",
      fishModifierName: "Золотая",
      fishModifierRarity: "Редкий",
    });

    const page = await repo.getInventoryPage(1, -100, 1, 5);
    expect(page.fishes).toEqual([
      expect.objectContaining({
        name: "Окунь",
        fishModifierId: "golden",
        fishModifierName: "Золотая",
        fishModifierRarity: "Редкий",
      }),
      expect.objectContaining({
        name: "Legacy",
        fishModifierId: null,
        fishModifierName: null,
        fishModifierRarity: null,
      }),
    ]);
    // A trade shows the real value: the modifier travels with the fish details.
    const requestedId = (await repo.getInventoryPage(2, -100, 1, 5)).fishes[0]!.id;
    const created = await repo.createTrade({
      chatId: -100,
      initiatorUserId: 1,
      initiatorFirstName: "Player",
      targetUserId: 2,
      targetFirstName: "Other",
      offer: { kind: "fish", offeredFishId: page.fishes[0]!.id },
      requestedFishId: requestedId,
    });
    expect(created.status).toBe("created");
    if (created.status !== "created") return;
    expect(created.trade.offer).toEqual({
      kind: "fish",
      fish: expect.objectContaining({
        id: page.fishes[0]!.id,
        fishModifierId: "golden",
        fishModifierName: "Золотая",
        fishModifierRarity: "Редкий",
      }),
    });
    expect(created.trade.requestedFish).toEqual(
      expect.objectContaining({ name: "Щука", fishModifierId: null, fishModifierName: null, fishModifierRarity: null }),
    );
    expect(await repo.getTrade(created.trade.id)).toEqual(created.trade);

    // Selling keeps the stored modifier data on the row itself.
    expect(await repo.sellFish(1, -100, page.fishes[0]!.id)).toEqual({ status: "sold", count: 1, total: 355.25 });
    const soldRows = (await sql!`SELECT fish_modifier_id, fish_modifier_name, fish_modifier_rarity
      FROM caught_fishes WHERE id = ${page.fishes[0]!.id}`) as Array<Record<string, unknown>>;
    expect(soldRows[0]).toEqual({ fish_modifier_id: "golden", fish_modifier_name: "Золотая", fish_modifier_rarity: "Редкий" });

    // The latest remaining catch is returned together with its modifier fields.
    expect(await repo.deleteLastCatch(1, -100)).toMatchObject({
      fishName: "Legacy",
      fishModifierId: null,
      fishModifierName: null,
      fishModifierRarity: null,
    });
  });

  test("reports the exact missing recipe rarity without changing resources", async () => {
    await migrateSchema(sql!);
    const repo = createRepo(sql!);
    await repo.ensureFisher(1, -100, "Player");
    for (const price of [100, 200, 300, 400]) await createAvailableCatch(1, -100, 1, price);
    await sql!`UPDATE fishers SET user_balance = 2500 WHERE user_id = 1 AND chat_id = -100`;

    expect(await repo.purchaseRod(1, -100, carbon)).toEqual({
      status: "insufficient_fish",
      point: 2,
      required: 2,
      available: 0,
    });
    expect((await repo.getFisher(1, -100))!.balance).toBe(2500);
    expect((await repo.getInventoryPage(1, -100, 1, 5)).totalCount).toBe(4);
    expect(await repo.listPurchasedRodIds(1, -100)).toEqual([]);
    expect(await repo.getEquippedRodId(1, -100)).toBe("basic");
  });

  test("purchase failures are atomic and success spends the cheapest exact recipe", async () => {
    await migrateSchema(sql!);
    const repo = createRepo(sql!);
    await repo.ensureFisher(1, -100, "Player");
    await createAvailableCatch(1, -100, 1, 400);
    await createAvailableCatch(1, -100, 1, 100);
    await createAvailableCatch(1, -100, 1, 300);
    await createAvailableCatch(1, -100, 1, 200);
    await createAvailableCatch(1, -100, 2, 600);
    await createAvailableCatch(1, -100, 2, 500);

    expect(await repo.purchaseRod(1, -100, titanium)).toEqual({ status: "missing_prerequisite", rodId: "carbon" });
    expect(await repo.purchaseRod(1, -100, carbon)).toEqual({ status: "insufficient_balance", required: 2500, available: 0 });
    await createAvailableCatch(1, -100, 1, 999);
    await createAvailableCatch(1, -100, 2, 999);
    await sql!`UPDATE fishers SET user_balance = 2500 WHERE user_id = 1 AND chat_id = -100`;
    const purchased = await repo.purchaseRod(1, -100, carbon);
    expect(purchased).toEqual({ status: "purchased", balance: 0 });
    expect(await repo.getEquippedRodId(1, -100)).toBe("carbon");
    expect(await repo.equipRod(1, -100, "basic")).toEqual({ status: "equipped" });
    expect(await repo.equipRod(1, -100, "carbon")).toEqual({ status: "equipped" });
    expect(await repo.listPurchasedRodIds(1, -100)).toEqual(["carbon"]);
    const rows = (await sql!`SELECT fish_price, inventory_state FROM caught_fishes ORDER BY fish_price`) as Array<{
      fish_price: number;
      inventory_state: string;
    }>;
    expect(rows).toEqual([
      { fish_price: 100, inventory_state: "spent" },
      { fish_price: 200, inventory_state: "spent" },
      { fish_price: 300, inventory_state: "spent" },
      { fish_price: 400, inventory_state: "spent" },
      { fish_price: 500, inventory_state: "spent" },
      { fish_price: 600, inventory_state: "spent" },
      { fish_price: 999, inventory_state: "available" },
      { fish_price: 999, inventory_state: "available" },
    ]);
  });

  test("races sale and purchase transitions without duplicate grants", async () => {
    await migrateSchema(sql!);
    const repo = createRepo(sql!);
    await repo.ensureFisher(1, -100, "Player");
    await createAvailableCatch(1, -100, 1, 150);
    const fishId = (await repo.getInventoryPage(1, -100, 1, 5)).fishes[0]!.id;
    const sales = await Promise.all([repo.sellFish(1, -100, fishId), repo.sellFish(1, -100, fishId)]);
    expect(sales.filter((result) => result.status === "sold")).toHaveLength(1);
    expect((await repo.getFisher(1, -100))!.balance).toBe(150);

    for (const price of [100, 200, 300, 400]) await createAvailableCatch(1, -100, 1, price);
    for (const price of [500, 600]) await createAvailableCatch(1, -100, 2, price);
    await sql!`UPDATE fishers SET user_balance = 2500 WHERE user_id = 1 AND chat_id = -100`;
    const purchases = await Promise.all([repo.purchaseRod(1, -100, carbon), repo.purchaseRod(1, -100, carbon)]);
    expect(purchases.filter((result) => result.status === "purchased")).toHaveLength(1);
    expect(purchases.filter((result) => result.status === "already_owned")).toHaveLength(1);
  });

  test("multiplyBalance scales only the selected user and chat balance", async () => {
    await migrateSchema(sql!);
    const repo = createRepo(sql!);
    await repo.ensureFisher(1, -100, "Player");
    await repo.ensureFisher(1, -200, "Player");
    await sql!`UPDATE fishers SET user_balance = 250 WHERE (user_id, chat_id) IN ((1, -100), (1, -200))`;

    expect(await repo.multiplyBalance(1, -100, 1.2)).toBe(300);
    expect((await repo.getFisher(1, -100))!.balance).toBe(300);
    expect((await repo.getFisher(1, -200))!.balance).toBe(250);
  });
});

describe.skipIf(databaseUrl === undefined)("Repo fishing nets integration", () => {
  beforeEach(async () => {
    await resetSchema();
  });

  function netCatch(userId: number, chatId: number, fishName: string): CatchInsert {
    return { username: "Игрок", userId, chatId, fishName, rarity: "Обычный", point: 1, sizeCm: 12, weightG: 138, price: 250, fishModifierId: null, fishModifierName: null, fishModifierRarity: null };
  }

  test("duplicate casts keep one row and return the original cast time", async () => {
    await migrateSchema(sql!);
    const repo = createRepo(sql!);

    expect(await repo.castFishingNet(9, -100, "Игрок", 1_000)).toBe(1_000);
    expect(await repo.castFishingNet(9, -100, "Игрок", 2_000)).toBe(1_000);

    expect(await repo.getFishingNet(9, -100)).toEqual({
      userId: 9,
      chatId: -100,
      firstName: "Игрок",
      castAt: 1_000,
      readyNotifiedAt: null,
    });
    expect(await repo.getFishingNet(8, -100)).toBeNull();
    expect(await repo.getFishingNet(9, -200)).toBeNull();
  });

  test("collecting before the deadline leaves the net row and inventory untouched", async () => {
    await migrateSchema(sql!);
    const repo = createRepo(sql!);
    await repo.castFishingNet(9, -100, "Игрок", 5_000);

    const result = await repo.collectFishingNet(9, -100, 5_000 + NET_DURATION_SECONDS - 1, [netCatch(9, -100, "Окунь")]);

    expect(result).toEqual({ status: "not_ready", castAt: 5_000 });
    expect(await repo.getFishingNet(9, -100)).not.toBeNull();
    expect(await repo.countUserFishes(9, -100)).toBe(0);
  });

  test("boundary collection atomically stores every catch and removes the net exactly once", async () => {
    await migrateSchema(sql!);
    const repo = createRepo(sql!);
    await repo.castFishingNet(9, -100, "Игрок", 5_000);
    const catches = ["Окунь", "Лещ", "Карп"].map((name) => netCatch(9, -100, name));
    catches[2]!.fishModifierId = "abyssal";
    catches[2]!.fishModifierName = "Бездна";
    catches[2]!.fishModifierRarity = "Мифический";

    expect(await repo.collectFishingNet(9, -100, 5_000 + NET_DURATION_SECONDS, catches)).toEqual({
      status: "collected",
      castAt: 5_000,
    });
    expect(await repo.getFishingNet(9, -100)).toBeNull();
    expect(await repo.countUserFishes(9, -100)).toBe(3);
    const modifierRows = (await sql!`SELECT fish_name, fish_modifier_id, fish_modifier_name, fish_modifier_rarity
      FROM caught_fishes WHERE fish_modifier_id IS NOT NULL`) as Array<Record<string, unknown>>;
    expect(modifierRows).toEqual([
      { fish_name: "Карп", fish_modifier_id: "abyssal", fish_modifier_name: "Бездна", fish_modifier_rarity: "Мифический" },
    ]);

    const replay = await repo.collectFishingNet(9, -100, 5_000 + NET_DURATION_SECONDS + 10, catches);
    expect(replay).toEqual({ status: "not_cast" });
    expect(await repo.countUserFishes(9, -100)).toBe(3);
  });

  test("readiness listing and notification marking cover exactly the due unnotified nets", async () => {
    await migrateSchema(sql!);
    const repo = createRepo(sql!);
    const now = 100_000;
    await repo.castFishingNet(1, -100, "Ранний", now - 10);
    await repo.castFishingNet(2, -100, "Готова", now - NET_DURATION_SECONDS - 10);
    await repo.castFishingNet(3, -200, "Другая группа", now - NET_DURATION_SECONDS - 5);
    await repo.castFishingNet(4, -100, "Уведомлён", now - NET_DURATION_SECONDS - 20);
    await repo.markFishingNetReadyNotified(4, -100, now - 50);

    const rows = await repo.listReadyUnnotifiedFishingNets(now);
    expect(rows.map((row) => [row.userId, row.chatId])).toEqual([
      [2, -100],
      [3, -200],
    ]);

    await repo.markFishingNetReadyNotified(2, -100, now);
    const rest = await repo.listReadyUnnotifiedFishingNets(now);
    expect(rest.map((row) => row.userId)).toEqual([3]);
  });
});

describe.skipIf(databaseUrl === undefined)("Repo trades integration", () => {
  beforeEach(async () => {
    await resetSchema();
  });

  /** Narrows a createTrade result to its persisted row, failing the test on stale. */
  function tradeOf(created: CreateTradeResult): TradeRow {
    if (created.status !== "created") throw new Error(`expected trade creation, got ${created.status}`);
    return created.trade;
  }

  async function seedTraders(): Promise<void> {
    await migrateSchema(sql!);
    await sql!`INSERT INTO fishers (user_id, chat_id, user_first_name, user_balance)
      VALUES (1, -100, 'Иван', 0), (2, -100, 'Аня', 0)`;
  }

  async function fishRow(id: number): Promise<{ user_id: number; username: string; inventory_state: string }> {
    const rows = (await sql!`SELECT user_id, username, inventory_state FROM caught_fishes WHERE id = ${id}`) as Array<{
      user_id: unknown;
      username: string;
      inventory_state: string;
    }>;
    const row = rows[0]!;
    return { user_id: Number(row.user_id), username: row.username, inventory_state: row.inventory_state };
  }

  test("persists a pending trade only from distinct available catches in expected hands", async () => {
    await seedTraders();
    const repo = createRepo(sql!);
    await createAvailableCatch(1, -100, 1, 100, "Окунь");
    await createAvailableCatch(2, -100, 2, 200, "Щука");
    const offeredId = (await repo.getInventoryPage(1, -100, 1, 5)).fishes[0]!.id;
    const requestedId = (await repo.getInventoryPage(2, -100, 1, 5)).fishes[0]!.id;
    const base = {
      chatId: -100,
      initiatorUserId: 1,
      initiatorFirstName: "Иван",
      targetUserId: 2,
      targetFirstName: "Аня",
    };

    // Requested fish must belong to the target.
    expect(
      await repo.createTrade({ ...base, offer: { kind: "fish", offeredFishId: requestedId }, requestedFishId: offeredId }),
    ).toEqual({ status: "stale" });
    // The same catch cannot be both sides of the deal.
    expect(
      await repo.createTrade({ ...base, offer: { kind: "fish", offeredFishId: offeredId }, requestedFishId: offeredId }),
    ).toEqual({ status: "stale" });
    // Money offers must be positive.
    expect(await repo.createTrade({ ...base, offer: { kind: "money", amount: 0 }, requestedFishId: requestedId })).toEqual({
      status: "stale",
    });

    const created = await repo.createTrade({
      ...base,
      offer: { kind: "fish", offeredFishId: offeredId },
      requestedFishId: requestedId,
    });
    expect(created.status).toBe("created");
    if (created.status !== "created") return;
    expect(created.trade).toMatchObject({
      chatId: -100,
      initiatorUserId: 1,
      targetUserId: 2,
      status: "pending",
      offer: { kind: "fish" },
    });
    expect(created.trade.offer).toEqual({
      kind: "fish",
      fish: expect.objectContaining({ id: offeredId, name: "Окунь", price: 100 }),
    });
    expect(created.trade.requestedFish).toEqual(expect.objectContaining({ id: requestedId, name: "Щука", price: 200 }));
    expect(await repo.getTrade(created.trade.id)).toEqual(created.trade);
  });

  test("database constraints enforce terminal statuses and exactly one positive offer", async () => {
    await seedTraders();
    const repo = createRepo(sql!);
    await createAvailableCatch(1, -100, 1, 100);
    await createAvailableCatch(2, -100, 2, 200);
    const offeredId = (await repo.getInventoryPage(1, -100, 1, 5)).fishes[0]!.id;
    const requestedId = (await repo.getInventoryPage(2, -100, 1, 5)).fishes[0]!.id;
    const insertWith = (offeredFishId: number | null, offeredMoney: number | null, status: string): Promise<unknown> =>
      sql!`INSERT INTO trades (chat_id, initiator_user_id, initiator_first_name, target_user_id, target_first_name,
        offered_fish_id, offered_money, requested_fish_id, status)
        VALUES (-100, 1, 'Иван', 2, 'Аня', ${offeredFishId}, ${offeredMoney}, ${requestedId}, ${status})`;

    // Bun SQL promises do not resolve through expect().rejects; catch directly.
    const rejected = async (task: Promise<unknown>): Promise<boolean> => {
      try {
        await task;
        return false;
      } catch {
        return true;
      }
    };

    // Both offer fields set → violates the exactly-one-offer constraint.
    expect(await rejected(insertWith(offeredId, 5, "pending"))).toBeTrue();
    // Non-positive money → violates the same constraint.
    expect(await rejected(insertWith(null, -5, "pending"))).toBeTrue();
    // Unknown status → violates the status constraint.
    expect(await rejected(insertWith(null, 5, "cancelled"))).toBeTrue();
    // A well-formed money offer persists.
    expect(await rejected(insertWith(null, 5, "pending"))).toBeFalse();
  });

  test("accepted fish-for-fish swaps user_id and username only in that chat", async () => {
    await seedTraders();
    const repo = createRepo(sql!);
    await createAvailableCatch(1, -100, 1, 100, "Окунь");
    await createAvailableCatch(2, -100, 2, 200, "Щука");
    await createAvailableCatch(1, -200, 1, 50, "Другая");
    const offeredId = (await repo.getInventoryPage(1, -100, 1, 5)).fishes[0]!.id;
    const requestedId = (await repo.getInventoryPage(2, -100, 1, 5)).fishes[0]!.id;
    const created = await repo.createTrade({
      chatId: -100,
      initiatorUserId: 1,
      initiatorFirstName: "Иван",
      targetUserId: 2,
      targetFirstName: "Аня",
      offer: { kind: "fish", offeredFishId: offeredId },
      requestedFishId: requestedId,
    });
    expect(created.status).toBe("created");

    expect(await repo.acceptTrade(tradeOf(created).id, 2, -100)).toEqual({ status: "accepted" });

    expect(await fishRow(offeredId)).toEqual({ user_id: 2, username: "Аня", inventory_state: "available" });
    expect(await fishRow(requestedId)).toEqual({ user_id: 1, username: "Иван", inventory_state: "available" });
    const otherChat = (await sql!`SELECT user_id FROM caught_fishes WHERE fish_name = 'Другая'`) as Array<{
      user_id: number;
    }>;
    expect(Number(otherChat[0]!.user_id)).toBe(1);
    expect((await repo.getFisher(1, -100))!.balance).toBe(0);
    expect((await repo.getFisher(2, -100))!.balance).toBe(0);
    expect((await repo.getTrade(tradeOf(created).id))!.status).toBe("accepted");
  });

  test("accepted money-for-fish moves exact two-decimal balances and the fish", async () => {
    await seedTraders();
    const repo = createRepo(sql!);
    await sql!`UPDATE fishers SET user_balance = 10.25 WHERE user_id = 1 AND chat_id = -100`;
    await createAvailableCatch(2, -100, 2, 200, "Щука");
    const requestedId = (await repo.getInventoryPage(2, -100, 1, 5)).fishes[0]!.id;
    const created = await repo.createTrade({
      chatId: -100,
      initiatorUserId: 1,
      initiatorFirstName: "Иван",
      targetUserId: 2,
      targetFirstName: "Аня",
      offer: { kind: "money", amount: 7.31 },
      requestedFishId: requestedId,
    });
    expect(created.status).toBe("created");

    expect(await repo.acceptTrade(tradeOf(created).id, 2, -100)).toEqual({ status: "accepted" });

    expect((await repo.getFisher(1, -100))!.balance).toBeCloseTo(2.94, 10);
    expect((await repo.getFisher(2, -100))!.balance).toBeCloseTo(7.31, 10);
    expect(await fishRow(requestedId)).toEqual({ user_id: 1, username: "Иван", inventory_state: "available" });
  });

  test("decline leaves both inventories and balances unchanged", async () => {
    await seedTraders();
    const repo = createRepo(sql!);
    await sql!`UPDATE fishers SET user_balance = 50 WHERE user_id = 1 AND chat_id = -100`;
    await createAvailableCatch(2, -100, 2, 200, "Щука");
    const requestedId = (await repo.getInventoryPage(2, -100, 1, 5)).fishes[0]!.id;
    const created = await repo.createTrade({
      chatId: -100,
      initiatorUserId: 1,
      initiatorFirstName: "Иван",
      targetUserId: 2,
      targetFirstName: "Аня",
      offer: { kind: "money", amount: 7.31 },
      requestedFishId: requestedId,
    });

    expect(await repo.declineTrade(tradeOf(created).id, 2, -100)).toEqual({ status: "declined" });

    expect((await repo.getFisher(1, -100))!.balance).toBe(50);
    expect((await repo.getFisher(2, -100))!.balance).toBe(0);
    expect(await fishRow(requestedId)).toEqual({ user_id: 2, username: "Test", inventory_state: "available" });
    // A replayed decline or a foreign press mutates nothing further.
    expect(await repo.declineTrade(tradeOf(created).id, 2, -100)).toEqual({ status: "unavailable" });
    expect(await repo.declineTrade(tradeOf(created).id, 1, -100)).toEqual({ status: "not_target" });
  });

  test("an offered fish made unavailable closes the trade without partial updates", async () => {
    await seedTraders();
    const repo = createRepo(sql!);
    await createAvailableCatch(1, -100, 1, 100, "Окунь");
    await createAvailableCatch(2, -100, 2, 200, "Щука");
    const offeredId = (await repo.getInventoryPage(1, -100, 1, 5)).fishes[0]!.id;
    const requestedId = (await repo.getInventoryPage(2, -100, 1, 5)).fishes[0]!.id;
    const created = await repo.createTrade({
      chatId: -100,
      initiatorUserId: 1,
      initiatorFirstName: "Иван",
      targetUserId: 2,
      targetFirstName: "Аня",
      offer: { kind: "fish", offeredFishId: offeredId },
      requestedFishId: requestedId,
    });
    await sql!`UPDATE caught_fishes SET inventory_state = 'sold' WHERE id = ${offeredId}`;

    expect(await repo.acceptTrade(tradeOf(created).id, 2, -100)).toEqual({ status: "unavailable" });

    expect(await fishRow(offeredId)).toEqual({ user_id: 1, username: "Test", inventory_state: "sold" });
    expect(await fishRow(requestedId)).toEqual({ user_id: 2, username: "Test", inventory_state: "available" });
    expect((await repo.getTrade(tradeOf(created).id))!.status).toBe("unavailable");
  });

  test("a drained buyer balance closes the money trade untouched", async () => {
    await seedTraders();
    const repo = createRepo(sql!);
    await sql!`UPDATE fishers SET user_balance = 1 WHERE user_id = 1 AND chat_id = -100`;
    await createAvailableCatch(2, -100, 2, 200, "Щука");
    const requestedId = (await repo.getInventoryPage(2, -100, 1, 5)).fishes[0]!.id;
    const created = await repo.createTrade({
      chatId: -100,
      initiatorUserId: 1,
      initiatorFirstName: "Иван",
      targetUserId: 2,
      targetFirstName: "Аня",
      offer: { kind: "money", amount: 7.31 },
      requestedFishId: requestedId,
    });
    expect(created.status).toBe("created");

    expect(await repo.acceptTrade(tradeOf(created).id, 2, -100)).toEqual({ status: "unavailable" });

    expect((await repo.getFisher(1, -100))!.balance).toBe(1);
    expect((await repo.getFisher(2, -100))!.balance).toBe(0);
    expect(await fishRow(requestedId)).toEqual({ user_id: 2, username: "Test", inventory_state: "available" });
  });

  test("simultaneous accepts move resources exactly once", async () => {
    await seedTraders();
    const repo = createRepo(sql!);
    await createAvailableCatch(1, -100, 1, 100, "Окунь");
    await createAvailableCatch(2, -100, 2, 200, "Щука");
    const offeredId = (await repo.getInventoryPage(1, -100, 1, 5)).fishes[0]!.id;
    const requestedId = (await repo.getInventoryPage(2, -100, 1, 5)).fishes[0]!.id;
    const created = await repo.createTrade({
      chatId: -100,
      initiatorUserId: 1,
      initiatorFirstName: "Иван",
      targetUserId: 2,
      targetFirstName: "Аня",
      offer: { kind: "fish", offeredFishId: offeredId },
      requestedFishId: requestedId,
    });
    expect(created.status).toBe("created");

    const results = await Promise.all([
      repo.acceptTrade(tradeOf(created).id, 2, -100),
      repo.acceptTrade(tradeOf(created).id, 2, -100),
    ]);

    expect(results.filter((result) => result.status === "accepted")).toHaveLength(1);
    expect(results.filter((result) => result.status === "unavailable")).toHaveLength(1);
    expect(await fishRow(offeredId)).toEqual({ user_id: 2, username: "Аня", inventory_state: "available" });
    expect(await fishRow(requestedId)).toEqual({ user_id: 1, username: "Иван", inventory_state: "available" });
  });
});
