import { SQL } from "bun";

export type FishTemplateRow = { id: number; name: string; rarity: string; point: number };
export type FishTemplateInsert = { name: string; rarity: string; point: number };
export type FisherRow = { userId: number; chatId: number; firstName: string; balance: number };
export type TopFisherRow = { firstName: string; total: number };
export type CatchInsert = {
  username: string;
  userId: number;
  chatId: number;
  fishName: string;
  rarity: string;
  point: number;
  sizeCm: number;
  weightG: number;
  price: number;
};

const SCHEMA_STATEMENTS = [
  `CREATE TABLE IF NOT EXISTS fishes (
  fish_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  fish_name TEXT NOT NULL,
  fish_rarity TEXT NOT NULL,
  fish_rarity_point INTEGER NOT NULL
)`,
  `CREATE TABLE IF NOT EXISTS fishers (
  user_id BIGINT NOT NULL,
  chat_id BIGINT NOT NULL,
  user_first_name TEXT NOT NULL,
  user_balance DOUBLE PRECISION NOT NULL DEFAULT 0,
  PRIMARY KEY (user_id, chat_id)
)`,
  `CREATE TABLE IF NOT EXISTS caught_fishes (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username TEXT NOT NULL,
  user_id BIGINT NOT NULL,
  fish_name TEXT NOT NULL,
  fish_weight DOUBLE PRECISION NOT NULL,
  fish_size DOUBLE PRECISION NOT NULL,
  fish_rarity TEXT NOT NULL,
  fish_rarity_point INTEGER NOT NULL,
  fish_price DOUBLE PRECISION NOT NULL,
  chat_id BIGINT NOT NULL
)`,
  `CREATE TABLE IF NOT EXISTS catch_time (
  user_id BIGINT NOT NULL,
  chat_id BIGINT NOT NULL,
  last_catch_time DOUBLE PRECISION NOT NULL,
  PRIMARY KEY (user_id, chat_id)
)`,
];

export function createSql(databaseUrl: string): SQL {
  return new SQL(databaseUrl);
}

export async function migrateSchema(sql: SQL): Promise<void> {
  for (const statement of SCHEMA_STATEMENTS) {
    await sql.unsafe(statement);
  }
}

/**
 * Postgres BIGINT surfaces as number, string, or BigInt depending on the
 * driver; coerce every integer column through this so the repo API is stable.
 */
function asNumber(value: unknown): number {
  return typeof value === "number" ? value : Number(value);
}

export type Repo = {
  ensureFisher(userId: number, chatId: number, firstName: string): Promise<void>;
  addBalance(userId: number, chatId: number, delta: number): Promise<void>;
  recordCatchWithBalance(catch_: CatchInsert, delta: number): Promise<void>;
  getCatchTime(userId: number, chatId: number): Promise<number | null>;
  upsertCatchTime(userId: number, chatId: number, unixSeconds: number): Promise<void>;
  getFisher(userId: number, chatId: number): Promise<FisherRow | null>;
  listTemplates(): Promise<FishTemplateRow[]>;
  replaceAllTemplates(templates: FishTemplateInsert[]): Promise<number>;
  getTopFishers(chatId: number, limit?: number): Promise<TopFisherRow[]>;
  sumUserFishPrice(userId: number, chatId: number): Promise<number>;
  countUserFishes(userId: number, chatId: number): Promise<number>;
  countUserFishesByRarity(userId: number, chatId: number, point: number): Promise<number>;
  insertTemplate(name: string, rarity: string, point: number): Promise<number>;
  deleteTemplate(id: number): Promise<void>;
  loadAllTemplates(): Promise<FishTemplateInsert[]>;
};

export function createRepo(sql: SQL): Repo {
  return {
    async ensureFisher(userId: number, chatId: number, firstName: string): Promise<void> {
      await sql`INSERT INTO fishers (user_id, chat_id, user_first_name, user_balance)
        VALUES (${userId}, ${chatId}, ${firstName}, 0)
        ON CONFLICT DO NOTHING`;
    },
    async addBalance(userId: number, chatId: number, delta: number): Promise<void> {
      await sql`UPDATE fishers SET user_balance = user_balance + ${delta}
        WHERE user_id = ${userId} AND chat_id = ${chatId}`;
    },
    async recordCatchWithBalance(catch_: CatchInsert, delta: number): Promise<void> {
      await sql.begin(async (tx) => {
        await tx`INSERT INTO caught_fishes
          (username, user_id, fish_name, fish_weight, fish_size, fish_rarity, fish_rarity_point, fish_price, chat_id)
          VALUES (${catch_.username}, ${catch_.userId}, ${catch_.fishName}, ${catch_.weightG}, ${catch_.sizeCm},
          ${catch_.rarity}, ${catch_.point}, ${catch_.price}, ${catch_.chatId})`;
        await tx`UPDATE fishers SET user_balance = user_balance + ${delta}
          WHERE user_id = ${catch_.userId} AND chat_id = ${catch_.chatId}`;
      });
    },
    async getCatchTime(userId: number, chatId: number): Promise<number | null> {
      const rows = (await sql`SELECT last_catch_time FROM catch_time
        WHERE user_id = ${userId} AND chat_id = ${chatId}`) as Array<{ last_catch_time: unknown }>;
      const row = rows[0];
      return row === undefined ? null : asNumber(row.last_catch_time);
    },
    async upsertCatchTime(userId: number, chatId: number, unixSeconds: number): Promise<void> {
      await sql`INSERT INTO catch_time (user_id, chat_id, last_catch_time)
        VALUES (${userId}, ${chatId}, ${unixSeconds})
        ON CONFLICT (user_id, chat_id) DO UPDATE SET last_catch_time = EXCLUDED.last_catch_time`;
    },
    async getFisher(userId: number, chatId: number): Promise<FisherRow | null> {
      const rows = (await sql`SELECT user_id, chat_id, user_first_name, user_balance FROM fishers
        WHERE user_id = ${userId} AND chat_id = ${chatId}`) as Array<Record<string, unknown>>;
      const row = rows[0];
      if (row === undefined) return null;
      return {
        userId: asNumber(row.user_id),
        chatId: asNumber(row.chat_id),
        firstName: String(row.user_first_name),
        balance: asNumber(row.user_balance),
      };
    },
    async getTopFishers(chatId: number, limit = 10): Promise<TopFisherRow[]> {
      const rows = (await sql`SELECT f.user_first_name, COALESCE(SUM(c.fish_price), 0) AS total
        FROM fishers f
        LEFT JOIN caught_fishes c ON c.user_id = f.user_id AND c.chat_id = f.chat_id
        WHERE f.chat_id = ${chatId}
        GROUP BY f.user_id, f.user_first_name
        ORDER BY total DESC
        LIMIT ${limit}`) as Array<Record<string, unknown>>;
      return rows.map((row) => ({
        firstName: String(row.user_first_name),
        total: asNumber(row.total),
      }));
    },
    async sumUserFishPrice(userId: number, chatId: number): Promise<number> {
      const rows = (await sql`SELECT COALESCE(SUM(fish_price), 0) AS total FROM caught_fishes
        WHERE user_id = ${userId} AND chat_id = ${chatId}`) as Array<Record<string, unknown>>;
      const row = rows[0];
      return row === undefined ? 0 : asNumber(row.total);
    },
    async countUserFishes(userId: number, chatId: number): Promise<number> {
      const rows = (await sql`SELECT COUNT(*)::int AS n FROM caught_fishes
        WHERE user_id = ${userId} AND chat_id = ${chatId}`) as Array<Record<string, unknown>>;
      const row = rows[0];
      return row === undefined ? 0 : asNumber(row.n);
    },
    async countUserFishesByRarity(userId: number, chatId: number, point: number): Promise<number> {
      const rows = (await sql`SELECT COUNT(*)::int AS n FROM caught_fishes
        WHERE user_id = ${userId} AND chat_id = ${chatId} AND fish_rarity_point = ${point}`) as Array<
        Record<string, unknown>
      >;
      const row = rows[0];
      return row === undefined ? 0 : asNumber(row.n);
    },
    async listTemplates(): Promise<FishTemplateRow[]> {
      const rows = (await sql`SELECT fish_id, fish_name, fish_rarity, fish_rarity_point
        FROM fishes ORDER BY fish_id`) as Array<Record<string, unknown>>;
      return rows.map((row) => ({
        id: asNumber(row.fish_id),
        name: String(row.fish_name),
        rarity: String(row.fish_rarity),
        point: asNumber(row.fish_rarity_point),
      }));
    },
    async replaceAllTemplates(templates: FishTemplateInsert[]): Promise<number> {
      return sql.begin(async (tx) => {
        await tx`DELETE FROM fishes`;
        for (const template of templates) {
          await tx`INSERT INTO fishes (fish_name, fish_rarity, fish_rarity_point)
            VALUES (${template.name}, ${template.rarity}, ${template.point})`;
        }
        return templates.length;
      });
    },
    async insertTemplate(name: string, rarity: string, point: number): Promise<number> {
      const rows = (await sql`INSERT INTO fishes (fish_name, fish_rarity, fish_rarity_point)
        VALUES (${name}, ${rarity}, ${point}) RETURNING fish_id`) as Array<Record<string, unknown>>;
      const row = rows[0];
      if (row === undefined) throw new Error("INSERT INTO fishes returned no fish_id");
      return asNumber(row.fish_id);
    },
    async deleteTemplate(id: number): Promise<void> {
      await sql`DELETE FROM fishes WHERE fish_id = ${id}`;
    },
    async loadAllTemplates(): Promise<FishTemplateInsert[]> {
      const rows = (await sql`SELECT fish_name, fish_rarity, fish_rarity_point FROM fishes
        ORDER BY fish_id`) as Array<Record<string, unknown>>;
      return rows.map((row) => ({
        name: String(row.fish_name),
        rarity: String(row.fish_rarity),
        point: asNumber(row.fish_rarity_point),
      }));
    },
  };
}
